#!/usr/bin/env python
"""
Add non-load commands to the database and generate code to recreate those
commands for archive purposes.

Usage: add_nonload_cmds.py [options] [cmd_set_arg1 ...]::

 Options:
   -h, --help            show this help message and exit
   --dbi=DBI             Database interface (sqlite|sybase)
   --server=SERVER       DBI server (<filename>|sybase)
   --check               Check for recent non-load commands and do not generate
                         commands
   --date=DATE           Date for command set
   --cmd-set=CMD_SET     Command set name
   --loglevel=LOGLEVEL   Log level (10=debug, 20=info, 30=warnings)
   --archive-file=FILE   Archive file for storing nonload cmd sets
  
Examples::

  # Print recent non-load commands
  add_nonload_cmds.py --check

  # Add a maneuver to RA, Dec, Roll = 10, 20, 30
  add_non_load_cmds --date '2009:065:12:13:14' --cmd-set manvr 10 20 30

  # Add an autonomous NSM transition (which also runs SCS107)
  add_non_load_cmds --date '2009:001:12:13:14' --cmd-set nsm
  add_non_load_cmds --date '2009:001:12:13:14' --cmd-set scs107
  
"""
import os
import sys
import logging
import time

import cmd_states
import Ska.DBI
from Chandra.Time import DateTime
import Ska.ParseCM

def get_options():
    from optparse import OptionParser
    parser = OptionParser(usage="usage: %prog [options] [cmd_set_arg1 ...]")
    parser.set_defaults()
    parser.add_option("--dbi",
                      default='sqlite',
                      help="Database interface (sqlite|sybase)")
    parser.add_option("--server",
                      default='test.db3',
                      help="DBI server (<filename>|sybase)")
    parser.add_option("--check",
                      action="store_true",
                      help="Check for recent non-load commands and do not generate commands")
    parser.add_option("--date",
                      help="Date for command set")
    parser.add_option("--cmd_set",
                      help="Command set name")
    parser.add_option("--loglevel",
                      type='int',
                      default=10,
                      help='Log level (10=debug, 20=info, 30=warnings)')
    parser.add_option("--archive-file",
                      default=os.path.join(os.environ['SKA'], 'share', 'states',
                                           'nonload_cmds_archive.py'),
                      help='Archive file for storing nonload cmd sets')
    (opt, args) = parser.parse_args()
    return (opt, args)

def log_cmds(cmds):
    logging.info('%-22s %-12s %-10s %-8s' % ('Date', 'CMD', 'TLMSID', 'MSID'))
    for cmd in cmds:
        if 'params' in cmd:
            paramstr = ' '.join(['%s=%s' % (key, str(val)) for key, val in cmd['params'].items()])
        else:
            paramstr = ''
        logging.info('%-22s %-12s %-10s %-8s %s' %
                     (cmd['date'], cmd['cmd'], str(cmd['tlmsid']), str(cmd['msid']), paramstr))

def main():
    opt, args = get_options()
    cmd_set_args = [Ska.ParseCM._coerce_type(x) for x in args]

    # Configure logging to emit msgs to stdout
    logging.basicConfig(level=opt.loglevel,
                        format='%(message)s',
                        stream=sys.stdout)

    logging.info('Connecting to db: dbi=%s server=%s' % (opt.dbi, opt.server))
    db = Ska.DBI.DBI(dbi=opt.dbi, server=opt.server, verbose=False)

    # Print information about recent non-load commands
    nl_cmds = db.fetchall("SELECT * FROM cmds WHERE timeline_id IS NULL ORDER BY date DESC")
    logging.info('Most recent non-load commands')
    log_cmds(nl_cmds[:10])
    logging.info('')

    # Jump out if only doing a check
    if opt.check:
        sys.exit(0)

    # Generate commands for the specified command set
    date = DateTime(opt.date).date
    cmds = cmd_states.generate_cmds(date, cmd_states.cmd_set(opt.cmd_set, *cmd_set_args))

    logging.info('Add following cmds to database')
    log_cmds(cmds)
    logging.info('')

    # Get confirmation about adding commands to database
    a = raw_input('Proceed [N]? ')
    if a.lower().strip().startswith('y'):
        logging.info('Adding cmds to database')
        cmd_states.insert_cmds_db(cmds, None, db)

        # Generate python that will add the same commands to the database
        try:
            f = open(opt.archive_file, 'a')
            print >>f, ''
            print >>f, '# Autogenerated by add_nonload_cmds.py at %s' % time.ctime()
            print >>f, '# date=%s cmd_set=%s args=%s' % (date, opt.cmd_set, ' '.join(args))
            print >>f, "cmds = generate_cmds('%s', cmd_set(%s))" % (date,
                                   ','.join(["'%s'" % opt.cmd_set] + args))
            print >>f, "cmd_states.insert_cmds_db(cmds, None, db)"
            f.close()
            logging.info('Appended cmd_set info to %s' % opt.archive_file)
        except:
            logging.info('Could not append cmd_set info to %s' % opt.archive_file)

if __name__ == '__main__':
    main()
